title: Jelita Anggraini
description: Portofolio Jelita Anggraini
url: "https://jelita009.github.io"
baseurl: ""  # HARUS kosong untuk user site

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
